use crate::{
    commands::run::run,
    configuration::Configuration,
    constants::COMPILER_TEST_WORKING_PATH,
    error::{panic_if_err, panic_with_msg, Errors},
    misc::{save_temporary_source, Set},
    parse::parser::check_grammar_accepts,
};
use std::{
    env,
    ffi::OsString,
    fs::{self, remove_file, File},
    io::{self, Write},
    path::{Path, PathBuf},
    process::{Child, Command, ExitStatus, Output, Stdio},
    sync::Once,
    thread::sleep,
    time::{Duration, Instant},
};
use tempfile::TempDir;

static BUILD_FIX: Once = Once::new();

/// Build the `fix` binary in release mode. Incremental compilation makes this a
/// fast freshness check once the binary is already built, so it is cheap for
/// every test to call. Thread-safe and builds at most once per test process:
/// the first caller runs `cargo build`, and every concurrent caller blocks in
/// `call_once` until that build finishes, so once this returns the binary at
/// `fix_binary_path()` is fully written and safe to execute.
fn build_fix() {
    BUILD_FIX.call_once(|| {
        let output = Command::new("cargo")
            .arg("build")
            .arg("--release")
            .output()
            .expect("Failed to run cargo build --release");

        if !output.status.success() {
            eprintln!("{}", String::from_utf8_lossy(&output.stderr));
            panic!("Failed to build fix in release mode");
        }
    });
}

/// Absolute path to the directory holding this worktree's freshly built `fix`
/// binary. Honors `CARGO_TARGET_DIR`; otherwise the crate's own `target`
/// directory. Because each git worktree compiles into its own target
/// directory, this resolves to a different binary per worktree — so tests
/// running concurrently in several worktrees exercise their own build and
/// never share an install location.
fn fix_binary_dir() -> PathBuf {
    let target_dir = env::var_os("CARGO_TARGET_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("target"));
    target_dir.join("release")
}

/// Absolute path to this worktree's freshly built `fix` binary.
fn fix_binary_path() -> PathBuf {
    fix_binary_dir().join("fix")
}

/// `PATH` with this worktree's build directory in front. A test project may
/// look `fix` up by name from its own subprocess (e.g. cp-library's IO test
/// runs `fix run` on a generated program), and such a lookup has to find the
/// binary under test.
fn path_env_with_fix_binary_dir() -> OsString {
    let mut dirs = vec![fix_binary_dir()];
    if let Some(path) = env::var_os("PATH") {
        dirs.extend(env::split_paths(&path));
    }
    env::join_paths(dirs).expect("The build directory path contains a path separator.")
}

/// A `Command` that runs this worktree's freshly built `fix` binary by absolute
/// path. Building is triggered (once) first, so the returned command always
/// targets a complete binary. The absolute path pins the run to the binary the
/// test just built; the `fix` on `PATH` is one a parallel worktree may be
/// overwriting.
pub fn fix_command() -> Command {
    build_fix();
    let mut command = Command::new(fix_binary_path());
    command.env("PATH", path_env_with_fix_binary_dir());
    command
}

/// A `fix build` command for a Fix source generated by a test, which is written into `dir` and
/// compiled at `opt_level`. The command runs in `dir`, so the compiler's working files land beside
/// the source. Use this for a test that drives the `fix` binary; a test that only needs the program
/// to run has `test_source`.
///
/// The returned command is ready to spawn, and the caller adds what it needs on top — an output
/// path, redirected streams. The compiler itself is built while this command is constructed, so a
/// caller that times the spawn measures the build of `source` alone.
pub fn fix_build_source_command(dir: &Path, source: &str, opt_level: &str) -> Command {
    let src_path = dir.join("generated.fix");
    fs::write(&src_path, source).expect("Failed to write the generated source file");
    let mut command = fix_command();
    command
        .arg("build")
        .arg("--file")
        .arg(&src_path)
        .arg("-O")
        .arg(opt_level)
        .current_dir(dir);
    command
}

/// Builds `source` at `opt_level` and runs the program it produces, returning what the program
/// printed with the surrounding whitespace removed. Fails the test unless the build finishes
/// within `timeout` and both the build and the program exit successfully.
///
/// Use this for a test whose subject is how long a build takes: the deadline turns a compiler that
/// has become superlinear in the shape being compiled into a failure, where waiting for it out
/// would occupy the machine for as long as the shape takes.
///
/// # Arguments
/// * `description` — what is being compiled, as a phrase that reads after "compiling": it is what
///   a failure names, e.g. "a chain of 2400 `let`s".
pub fn build_within_and_run(
    source: &str,
    opt_level: &str,
    timeout: Duration,
    description: &str,
) -> String {
    let temp_dir = TempDir::new().expect("Failed to create temp directory");
    let program_path = temp_dir.path().join("program");

    // The compiler's diagnostics go to a file, which is read once the child has exited. A pipe
    // left unread that long fills its buffer and blocks the very build being timed.
    let log_path = temp_dir.path().join("build.log");
    let log = File::create(&log_path).expect("Failed to create the build log");
    let log_for_stderr = log
        .try_clone()
        .expect("Failed to clone the build log handle");

    let mut command = fix_build_source_command(temp_dir.path(), source, opt_level);
    command
        .arg("-o")
        .arg(&program_path)
        .stdout(Stdio::from(log))
        .stderr(Stdio::from(log_for_stderr));
    let mut child = command.spawn().expect("Failed to execute fix build");
    let status = wait_within(&mut child, timeout, &format!("compiling {}", description));
    assert!(
        status.success(),
        "compiling {} failed: {}\n{}",
        description,
        status,
        fs::read_to_string(&log_path).expect("Failed to read the build log")
    );

    let output = Command::new(&program_path)
        .output()
        .expect("Failed to run the compiled program");
    assert!(
        output.status.success(),
        "the program compiled from {} exited with {}",
        description,
        output.status
    );
    String::from_utf8_lossy(&output.stdout).trim().to_string()
}

/// Which of a build's emitted LLVM IR files to read. The selection reads the file names
/// `Configuration::get_output_llvm_ir_path` gives them.
pub enum EmittedIr {
    /// Every module, as the code generator wrote it and as the pass pipeline left it.
    All,
    /// Each module as the code generator wrote it, before the LLVM pass pipeline ran.
    BeforeOptimization,
    /// Each module as the LLVM pass pipeline left it.
    AfterOptimization,
}

impl EmittedIr {
    /// Whether a file of the build directory named `name` is one this selection reads.
    fn selects(&self, name: &str) -> bool {
        let is_optimized = name.ends_with("_optimized.ll");
        match self {
            EmittedIr::All => name.ends_with(".ll"),
            EmittedIr::BeforeOptimization => name.ends_with(".ll") && !is_optimized,
            EmittedIr::AfterOptimization => is_optimized,
        }
    }
}

/// The LLVM IR a `--emit-llvm` build wrote into `dir`, concatenated in file-name order.
///
/// A build names its files after the compilation units it produced, so the files an earlier build
/// left in the same directory survive it. Give each build a directory of its own where the IR is to
/// be attributed to it.
pub fn emitted_llvm_ir(dir: &Path, which: EmittedIr) -> String {
    let mut paths = fs::read_dir(dir)
        .expect("Failed to read the build directory")
        .filter_map(|entry| {
            let path = entry.expect("Failed to read a directory entry").path();
            let name = path.file_name()?.to_str()?.to_string();
            which.selects(&name).then_some(path)
        })
        .collect::<Vec<_>>();
    paths.sort();
    assert!(
        !paths.is_empty(),
        "the build emitted no LLVM IR in {}",
        dir.display()
    );
    paths
        .iter()
        .map(|path| fs::read_to_string(path).expect("Failed to read an emitted LLVM IR file"))
        .collect::<Vec<_>>()
        .join("\n")
}

/// The functions `ir` defines, each paired with whether it carries the function attribute
/// `attribute`.
///
/// LLVM writes the attributes of a function as a reference to a group listed at the end of the
/// module — `define ... @f(...) #2 {` against `attributes #2 = { alwaysinline }` — so each `define`
/// line is read here against those listings.
pub fn llvm_functions_carrying(ir: &str, attribute: &str) -> Vec<(String, bool)> {
    // The groups holding `attribute`, by the number a `define` line names them with.
    let mut groups: Set<&str> = Set::default();
    for line in ir.lines() {
        let Some(listing) = line.strip_prefix("attributes ") else {
            continue;
        };
        let Some((group, attributes)) = listing.split_once('=') else {
            continue;
        };
        let holds = attributes
            .split(|c: char| !c.is_alphanumeric() && c != '_' && c != '-')
            .any(|word| word == attribute);
        if holds {
            groups.insert(group.trim());
        }
    }

    let mut functions = vec![];
    for line in ir.lines() {
        if !line.starts_with("define ") {
            continue;
        }
        let Some(name) = llvm_function_name(line) else {
            continue;
        };
        // The groups a function carries stand between its parameter list and its body.
        let after_parameters = line.rsplit_once(')').map_or("", |(_, tail)| tail);
        let carries = after_parameters
            .split_whitespace()
            .any(|token| groups.contains(token));
        functions.push((name.to_string(), carries));
    }
    functions
}

/// The name of the function a `define` line defines. A name that is not a bare identifier — which
/// every name the compiler mints for a Fix value is — stands quoted.
fn llvm_function_name(define_line: &str) -> Option<&str> {
    let after_sigil = define_line.split_once('@')?.1;
    match after_sigil.strip_prefix('"') {
        Some(quoted) => quoted.split_once('"').map(|(name, _)| name),
        None => after_sigil.split_once('(').map(|(name, _)| name),
    }
}

/// The bodies of the LLVM functions of `ir` whose names contain `name_part`, one string each.
pub fn llvm_function_bodies(ir: &str, name_part: &str) -> Vec<String> {
    let mut bodies = vec![];
    let mut current_body: Option<Vec<&str>> = None;
    for line in ir.lines() {
        if line.starts_with("define ") {
            current_body = line.contains(name_part).then(Vec::new);
        }
        if let Some(body) = current_body.as_mut() {
            body.push(line);
        }
        if line == "}" {
            if let Some(body) = current_body.take() {
                bodies.push(body.join("\n"));
            }
        }
    }
    bodies
}

#[cfg(test)]
mod tests {
    use super::EmittedIr;

    /// A build writes each module twice, once as generated and once as optimized, under names that
    /// differ only by a suffix. The selection reads that suffix, so it is pinned here: a selection
    /// that quietly widened would let a test asserting the absence of something in the generated
    /// code pass on the optimized code instead.
    #[test]
    fn test_emitted_ir_selects_by_the_optimization_suffix() {
        let generated = "Module-0123abcd.ll";
        let optimized = "Module-0123abcd_optimized.ll";
        let source_file = "generated.fix";

        assert!(EmittedIr::All.selects(generated) && EmittedIr::All.selects(optimized));
        assert!(!EmittedIr::All.selects(source_file));

        assert!(EmittedIr::BeforeOptimization.selects(generated));
        assert!(!EmittedIr::BeforeOptimization.selects(optimized));
        assert!(!EmittedIr::BeforeOptimization.selects(source_file));

        assert!(EmittedIr::AfterOptimization.selects(optimized));
        assert!(!EmittedIr::AfterOptimization.selects(generated));
        assert!(!EmittedIr::AfterOptimization.selects(source_file));
    }
}

/// Waits for `child` to exit and returns its status, killing it and failing the test once `timeout`
/// has passed. `description` names what was being waited for, and is what the failure reports.
pub fn wait_within(child: &mut Child, timeout: Duration, description: &str) -> ExitStatus {
    let deadline = Instant::now() + timeout;
    loop {
        if let Some(status) = child.try_wait().expect("Failed to poll the child process") {
            return status;
        }
        if Instant::now() >= deadline {
            let _ = child.kill();
            let _ = child.wait();
            panic!(
                "{} did not finish within {} seconds",
                description,
                timeout.as_secs()
            );
        }
        sleep(Duration::from_millis(50));
    }
}

/// Compiles `source` under `config` and runs the resulting program. The outer `Result` reports the
/// compilation, and the inner one the spawning of the compiled program.
fn run_source(
    source: &str,
    mut config: Configuration,
) -> Result<Result<Output, io::Error>, Errors> {
    const MAIN_RUN: &str = "main_run";
    let src = save_temporary_source(source, MAIN_RUN)?;
    config.add_user_source_file(src.file_path);
    run(config, false)
}

/// Compiles `source` under `config` and runs it, failing the test unless it exits with code 0. The
/// program's stdout and stderr are forwarded to the test's stderr, so a failing run shows what it
/// printed.
pub fn test_source(source: &str, config: Configuration) {
    let compile_result = run_source(source, config);
    let spawn_result = panic_if_err(compile_result);
    let output = spawn_result.unwrap();
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);
    if !stdout.is_empty() {
        eprintln!("{}", stdout);
    }
    if !stderr.is_empty() {
        eprintln!("{}", stderr);
    }
    let code = match output.status.code() {
        Some(code) => code,
        None => panic_with_msg("The process was terminated by signal."),
    };
    if code != 0 {
        panic_with_msg(&format!("The program exited with non-zero code: {}", code));
    }
}

/// Compile and run `source`, returning the process output. Panics if compilation fails or the
/// program cannot be spawned. Use this to assert on the program's stdout / stderr.
pub fn run_source_capture(source: &str, config: Configuration) -> Output {
    panic_if_err(run_source(source, config)).unwrap()
}

/// Verify that the pest grammar rejects `source` (parse-level
/// rejection). Use this for negative tests that want to assert "the
/// parser rejects this construct" without going through later
/// elaboration / typecheck stages.
pub fn assert_grammar_rejects(source: &str) {
    if check_grammar_accepts(source).is_ok() {
        panic_with_msg(&format!(
            "Grammar was expected to reject the source but accepted it.\nSource:\n{}",
            source
        ));
    }
}

/// Verify that the pest grammar accepts `source`. Use this for a positive parser regression
/// test that only needs the source to parse, without compiling or running it.
pub fn assert_grammar_accepts(source: &str) {
    if let Err(e) = check_grammar_accepts(source) {
        panic_with_msg(&format!(
            "Grammar was expected to accept the source but rejected it: {}\nSource:\n{}",
            e, source
        ));
    }
}

/// Run `source` and return the user-visible diagnostic text. Asserts
/// that compilation/execution did not succeed; panics if it did.
///
/// "User-visible diagnostic text" is one of:
///   - the rendered `Errors` if the elaborator returned `Err`;
///   - the `io::Error` string if the child process couldn't even
///     spawn;
///   - the captured stderr from the child process otherwise.
pub fn run_source_assert_failed(source: &str, config: Configuration) -> String {
    let compile_result = run_source(source, config);
    match compile_result {
        Err(errs) => errs.to_string(),
        Ok(Err(e)) => e.to_string(),
        Ok(Ok(output)) => {
            if output.status.code() == Some(0) {
                panic_with_msg("The source code was expected to fail, but succeeded.");
            }
            String::from_utf8_lossy(&output.stderr).to_string()
        }
    }
}

/// Verify that compilation fails and that the error message does NOT
/// contain `excluded_errmsg`. Used to confirm a genuine error is not
/// silently swallowed by some permissive feature (e.g. that the hole
/// feature does not accept code it was never meant to).
pub fn test_source_fail_excludes(source: &str, config: Configuration, excluded_errmsg: &str) {
    let errmsg = run_source_assert_failed(source, config);
    assert!(
        !errmsg.contains(excluded_errmsg),
        "Error message unexpectedly contained excluded text.\nShould not include:\n{}\n\nActual message:\n{}",
        excluded_errmsg,
        errmsg
    );
}

/// Compiles and runs `source`, and asserts that it fails with a diagnostic containing
/// `included_errmsg`.
pub fn test_source_fail(source: &str, config: Configuration, included_errmsg: &str) {
    let errmsg = run_source_assert_failed(source, config);
    assert!(errmsg.contains(included_errmsg),
        "Error message did not contain expected text.\nExpected to include:\n{}\n\nActual message:\n{}", included_errmsg, errmsg);
}

/// Whether `path` names a Fix source file.
fn is_fix_source(path: &Path) -> bool {
    path.extension().is_some_and(|extension| extension == "fix")
}

/// Runs each `*.fix` file directly under `dir` as a Fix program of its own, and each subdirectory of
/// `dir` as one Fix program made of all the `*.fix` files it contains. Hidden subdirectories are
/// skipped. Fails the test unless every program exits with code 0.
pub fn test_files_in_directory(dir: &Path) {
    let entries = fs::read_dir(dir).unwrap();
    for entry in entries {
        let path = entry.unwrap().path();
        let mut config = Configuration::develop_mode();
        if path.is_dir() {
            // Skip hidden directories.
            if path.file_name().unwrap().to_str().unwrap().starts_with(".") {
                continue;
            }

            // For each directory in "tests" directory, run Fix program which consists of "*.fix" files in the directory.
            let files = fs::read_dir(&path).unwrap();
            for file in files {
                let file = file.unwrap().path();
                if !is_fix_source(&file) {
                    continue;
                }
                config.add_user_source_file(file);
            }
        } else {
            // For each file which has extention "fix" in "tests" directory, run it as Fix program.
            if !is_fix_source(&path) {
                continue;
            }
            config.add_user_source_file(path.clone());
        }
        println!("[{}]:", path.to_string_lossy().to_string());
        let compile_result = run(config, false);
        let spawn_result = panic_if_err(compile_result);
        let output = spawn_result.unwrap();
        let code = output.status.code().unwrap();
        assert_eq!(code, 0);
        remove_file("test_process_text_file.txt").unwrap_or(());
    }
}

/// Compiles `c_src` with `gcc`, links the resulting object file into the Fix program `fix_src`, and
/// runs it, failing the test unless it exits with code 0. `test_name` names the intermediate C and
/// object files, so each test that calls this needs a name of its own.
pub fn test_source_with_c(fix_src: &str, c_src: &str, test_name: &str) {
    // Create a working directory.
    let _ = fs::create_dir_all(COMPILER_TEST_WORKING_PATH);

    // Save `c_source` to a file.
    let c_file_path = format!("{}/{}.c", COMPILER_TEST_WORKING_PATH, test_name);
    let mut file = File::create(&c_file_path).unwrap();
    file.write_all(c_src.as_bytes()).unwrap();

    // Build `c_source` into an object file.
    let o_file_path = format!("{}/{}.o", COMPILER_TEST_WORKING_PATH, test_name);
    let mut command = Command::new("gcc");
    let output = command
        .arg("-c")
        .arg("-o")
        .arg(&o_file_path)
        .arg(&c_file_path)
        .output()
        .expect("Failed to run gcc.");
    if output.stderr.len() > 0 {
        eprintln!(
            "{}",
            String::from_utf8(output.stderr)
                .unwrap_or("(failed to parse stderr from gcc as UTF8.)".to_string())
        );
    }

    // Link the object file to the Fix program.
    let mut config = Configuration::develop_mode();
    config.object_files.push(PathBuf::from(&o_file_path));

    // Run the Fix program.
    test_source(&fix_src, config);

    // Remove the object file.
    let _ = fs::remove_file(o_file_path);
}

/// Copies the directory `src` into `dst`, recursing into subdirectories and creating `dst` and its
/// subdirectories as needed.
pub fn copy_dir_recursive(src: &PathBuf, dst: &PathBuf) -> io::Result<()> {
    fs::create_dir_all(dst)?;
    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let file_type = entry.file_type()?;
        let src_path = entry.path();
        let dst_path = dst.join(entry.file_name());

        if file_type.is_dir() {
            copy_dir_recursive(&src_path, &dst_path)?;
        } else {
            fs::copy(&src_path, &dst_path)?;
        }
    }
    Ok(())
}

/// Copies the case projects under `cases_dir` into a temporary directory and returns it with the
/// path of `project` inside it. The projects are copied together because they refer to each other
/// by relative path.
///
/// # Arguments
/// * `cases_dir` — the directory holding the case projects, relative to the crate root.
pub fn setup_case_projects(cases_dir: &str, project: &str) -> (TempDir, PathBuf) {
    let temp_dir = TempDir::new().expect("Failed to create temp directory");
    let cases = Path::new(env!("CARGO_MANIFEST_DIR")).join(cases_dir);
    copy_dir_recursive(&cases, &temp_dir.path().to_path_buf()).expect("Failed to copy test cases");
    let project_dir = temp_dir.path().join(project);
    (temp_dir, project_dir)
}

/// Runs `fix` with `args` in `project_dir`.
pub fn run_fix(project_dir: &Path, args: &[&str]) -> Output {
    fix_command()
        .args(args)
        .current_dir(project_dir)
        .output()
        .expect("Failed to execute fix")
}

/// Asserts that `output` succeeded, quoting both streams otherwise.
///
/// # Arguments
/// * `what` — what the run was expected to do, so a failure says which expectation broke.
pub fn assert_succeeded(output: &Output, what: &str) {
    assert!(
        output.status.success(),
        "{}\nstdout: {}\nstderr: {}",
        what,
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );
}

/// Asserts that `output` failed, quoting both streams otherwise.
///
/// # Arguments
/// * `what` — what the run was expected to do, so a failure says which expectation broke.
pub fn assert_failed(output: &Output, what: &str) {
    assert!(
        !output.status.success(),
        "{}\nstdout: {}\nstderr: {}",
        what,
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );
}
