use crate::{
    commands::run::run,
    configuration::Configuration,
    constants::COMPILER_TEST_WORKING_PATH,
    error::{panic_if_err, panic_with_msg, Errors},
    misc::save_temporary_source,
    parse::parser::check_grammar_accepts,
};
use std::{
    env,
    ffi::OsString,
    fs::{self, remove_file, File},
    io::{self, Write},
    path::{Path, PathBuf},
    process::{Child, Command, ExitStatus, Output},
    sync::Once,
    thread::sleep,
    time::{Duration, Instant},
};

static BUILD_FIX: Once = Once::new();

/// Build the `fix` binary in release mode. Incremental compilation makes this a
/// fast freshness check once the binary is already built, so it is cheap for
/// every test to call. Thread-safe and builds at most once per test process:
/// the first caller runs `cargo build`, and every concurrent caller blocks in
/// `call_once` until that build finishes, so once this returns the binary at
/// `fix_binary_path()` is fully written and safe to execute.
fn build_fix() {
    BUILD_FIX.call_once(|| {
        let output = Command::new("cargo")
            .arg("build")
            .arg("--release")
            .output()
            .expect("Failed to run cargo build --release");

        if !output.status.success() {
            eprintln!("{}", String::from_utf8_lossy(&output.stderr));
            panic!("Failed to build fix in release mode");
        }
    });
}

/// Absolute path to the directory holding this worktree's freshly built `fix`
/// binary. Honors `CARGO_TARGET_DIR`; otherwise the crate's own `target`
/// directory. Because each git worktree compiles into its own target
/// directory, this resolves to a different binary per worktree — so tests
/// running concurrently in several worktrees exercise their own build and
/// never share an install location.
fn fix_binary_dir() -> PathBuf {
    let target_dir = env::var_os("CARGO_TARGET_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("target"));
    target_dir.join("release")
}

/// Absolute path to this worktree's freshly built `fix` binary.
fn fix_binary_path() -> PathBuf {
    fix_binary_dir().join("fix")
}

/// `PATH` with this worktree's build directory in front. A test project may
/// look `fix` up by name from its own subprocess (e.g. cp-library's IO test
/// runs `fix run` on a generated program), and such a lookup has to find the
/// binary under test.
fn path_env_with_fix_binary_dir() -> OsString {
    let mut dirs = vec![fix_binary_dir()];
    if let Some(path) = env::var_os("PATH") {
        dirs.extend(env::split_paths(&path));
    }
    env::join_paths(dirs).expect("The build directory path contains a path separator.")
}

/// A `Command` that runs this worktree's freshly built `fix` binary by absolute
/// path. Building is triggered (once) first, so the returned command always
/// targets a complete binary. Spawning `fix` this way runs the binary the test
/// just built rather than whatever `fix` is on `PATH`, which a parallel
/// worktree may be overwriting.
pub fn fix_command() -> Command {
    build_fix();
    let mut command = Command::new(fix_binary_path());
    command.env("PATH", path_env_with_fix_binary_dir());
    command
}

/// A `fix build` command for a Fix source generated by a test, which is written into `dir` and
/// compiled at `opt_level`. The command runs in `dir`, so the compiler's working files land beside
/// the source. Use this for a test that drives the `fix` binary; a test that only needs the program
/// to run has `test_source`.
///
/// The returned command is ready to spawn, and the caller adds what it needs on top — an output
/// path, redirected streams. The compiler itself is built while this command is constructed, so a
/// caller that times the spawn measures the build of `source` alone.
pub fn fix_build_source_command(dir: &Path, source: &str, opt_level: &str) -> Command {
    let src_path = dir.join("generated.fix");
    fs::write(&src_path, source).expect("Failed to write the generated source file");
    let mut command = fix_command();
    command
        .arg("build")
        .arg("--file")
        .arg(&src_path)
        .arg("-O")
        .arg(opt_level)
        .current_dir(dir);
    command
}

/// Compiles `source` at `opt_level` with `--emit-llvm` and returns the LLVM IR as code generation
/// wrote it, before the LLVM optimizer runs. A test that reads the IR is checking what the compiler
/// emitted, so it wants that module rather than the optimized one beside it.
///
/// # Arguments
/// * `test_name` — names the working directory under `COMPILER_TEST_WORKING_PATH`, so concurrent
///   tests do not share one. Pass `function_name!()`.
/// * `opt_level` — below `max` the program is split into several modules, and their IR is
///   concatenated; from `max` up it is one module, so a test that counts occurrences wants `max`.
pub fn emit_llvm_ir(source: &str, test_name: &str, opt_level: &str) -> String {
    let work_dir = PathBuf::from(format!("{}/{}", COMPILER_TEST_WORKING_PATH, test_name));
    let _ = fs::remove_dir_all(&work_dir);
    fs::create_dir_all(&work_dir).unwrap();
    // The command runs in `work_dir`, so the path it is given for the source has to be absolute.
    let work_dir = fs::canonicalize(&work_dir).unwrap();

    let output = fix_build_source_command(&work_dir, source, opt_level)
        .arg("--emit-llvm")
        .arg("--output")
        .arg("prog")
        .output()
        .unwrap();
    assert_eq!(
        output.status.code(),
        Some(0),
        "`fix build --emit-llvm` failed:\n{}",
        String::from_utf8_lossy(&output.stderr)
    );

    let mut module_paths = fs::read_dir(&work_dir)
        .unwrap()
        .map(|e| e.unwrap().path())
        .filter(|p| {
            let name = p.file_name().unwrap().to_string_lossy();
            name.ends_with(".ll") && !name.ends_with("_optimized.ll")
        })
        .collect::<Vec<_>>();
    module_paths.sort();
    assert!(
        !module_paths.is_empty(),
        "`fix build --emit-llvm` wrote no module"
    );
    module_paths
        .iter()
        .map(|p| fs::read_to_string(p).unwrap())
        .collect::<Vec<_>>()
        .join("\n")
}

/// Waits for `child` to exit and returns its status, killing it and failing the test once `timeout`
/// has passed. `description` names what was being waited for, and is what the failure reports.
pub fn wait_within(child: &mut Child, timeout: Duration, description: &str) -> ExitStatus {
    let deadline = Instant::now() + timeout;
    loop {
        if let Some(status) = child.try_wait().expect("Failed to poll the child process") {
            return status;
        }
        if Instant::now() >= deadline {
            let _ = child.kill();
            let _ = child.wait();
            panic!(
                "{} did not finish within {} seconds",
                description,
                timeout.as_secs()
            );
        }
        sleep(Duration::from_millis(50));
    }
}

/// Compiles `source` under `config` and runs the resulting program. The outer `Result` reports the
/// compilation, and the inner one the spawning of the compiled program.
fn run_source(
    source: &str,
    mut config: Configuration,
) -> Result<Result<Output, io::Error>, Errors> {
    const MAIN_RUN: &str = "main_run";
    let src = save_temporary_source(source, MAIN_RUN)?;
    config.add_user_source_file(src.file_path);
    run(config, false)
}

/// Compiles `source` under `config`, runs the resulting program and requires it to exit with status
/// zero, so a failing `assert` inside the Fix program fails the test. What the program wrote to
/// stdout and stderr is forwarded to the test's stderr, where it accompanies the failure.
pub fn test_source(source: &str, config: Configuration) {
    let res = run_source(source, config);
    let res = panic_if_err(res);
    let output = res.unwrap();
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);
    if !stdout.is_empty() {
        eprintln!("{}", stdout);
    }
    if !stderr.is_empty() {
        eprintln!("{}", stderr);
    }
    let code = match output.status.code() {
        Some(code) => code,
        None => panic_with_msg("The process was terminated by signal."),
    };
    if code != 0 {
        panic_with_msg(&format!("The program exited with non-zero code: {}", code));
    }
}

/// Compile and run `source`, returning the process output. Panics if compilation fails or the
/// program cannot be spawned. Use this to assert on the program's stdout / stderr.
pub fn run_source_capture(source: &str, config: Configuration) -> Output {
    panic_if_err(run_source(source, config)).unwrap()
}

/// Verify that the pest grammar rejects `source` (parse-level
/// rejection). Use this for negative tests that want to assert "the
/// parser rejects this construct" without going through later
/// elaboration / typecheck stages.
pub fn assert_grammar_rejects(source: &str) {
    if check_grammar_accepts(source).is_ok() {
        panic_with_msg(&format!(
            "Grammar was expected to reject the source but accepted it.\nSource:\n{}",
            source
        ));
    }
}

/// Verify that the pest grammar accepts `source`. Use this for a positive parser regression
/// test that only needs the source to parse, without compiling or running it.
pub fn assert_grammar_accepts(source: &str) {
    if let Err(e) = check_grammar_accepts(source) {
        panic_with_msg(&format!(
            "Grammar was expected to accept the source but rejected it: {}\nSource:\n{}",
            e, source
        ));
    }
}

/// Run `source` and return the user-visible diagnostic text. Asserts
/// that compilation/execution did not succeed; panics if it did.
///
/// "User-visible diagnostic text" is one of:
///   - the rendered `Errors` if the elaborator returned `Err`;
///   - the `io::Error` string if the child process couldn't even
///     spawn;
///   - the captured stderr from the child process otherwise.
pub fn run_source_assert_failed(source: &str, config: Configuration) -> String {
    let res = run_source(source, config);
    match res {
        Err(errs) => errs.to_string(),
        Ok(Err(e)) => e.to_string(),
        Ok(Ok(output)) => {
            if output.status.code() == Some(0) {
                panic_with_msg("The source code was expected to fail, but succeeded.");
            }
            String::from_utf8_lossy(&output.stderr).to_string()
        }
    }
}

/// Verify that compilation fails and that the error message does NOT
/// contain `excluded_errmsg`. Used to confirm a genuine error is not
/// silently swallowed by some permissive feature (e.g. that the hole
/// feature does not accept code it was never meant to).
pub fn test_source_fail_excludes(source: &str, config: Configuration, excluded_errmsg: &str) {
    let errmsg = run_source_assert_failed(source, config);
    assert!(
        !errmsg.contains(excluded_errmsg),
        "Error message unexpectedly contained excluded text.\nShould not include:\n{}\n\nActual message:\n{}",
        excluded_errmsg,
        errmsg
    );
}

/// Compiles and runs `source`, and asserts that it fails with a diagnostic containing
/// `included_errmsg`.
pub fn test_source_fail(source: &str, config: Configuration, included_errmsg: &str) {
    let errmsg = run_source_assert_failed(source, config);
    assert!(errmsg.contains(included_errmsg),
        "Error message did not contain expected text.\nExpected to include:\n{}\n\nActual message:\n{}", included_errmsg, errmsg);
}

/// Whether `path` names a Fix source file.
fn is_fix_source(path: &Path) -> bool {
    path.extension().is_some_and(|extension| extension == "fix")
}

/// Runs each `*.fix` file directly under `dir` as a Fix program of its own, and each subdirectory of
/// `dir` as one Fix program made of all the `*.fix` files it contains. Hidden subdirectories are
/// skipped. Fails the test unless every program exits with code 0.
pub fn test_files_in_directory(dir: &Path) {
    let entries = fs::read_dir(dir).unwrap();
    for entry in entries {
        let path = entry.unwrap().path();
        let mut config = Configuration::develop_mode();
        if path.is_dir() {
            // Skip hidden directories.
            if path.file_name().unwrap().to_str().unwrap().starts_with(".") {
                continue;
            }

            // For each directory in "tests" directory, run Fix program which consists of "*.fix" files in the directory.
            let files = fs::read_dir(&path).unwrap();
            for file in files {
                let file = file.unwrap().path();
                if !is_fix_source(&file) {
                    continue;
                }
                config.add_user_source_file(file);
            }
        } else {
            // For each file which has extention "fix" in "tests" directory, run it as Fix program.
            if !is_fix_source(&path) {
                continue;
            }
            config.add_user_source_file(path.clone());
        }
        println!("[{}]:", path.to_string_lossy().to_string());
        let res = run(config, false);
        let res = panic_if_err(res);
        let output = res.unwrap();
        let code = output.status.code().unwrap();
        assert_eq!(code, 0);
        remove_file("test_process_text_file.txt").unwrap_or(());
    }
}

/// Compiles `c_src` with `gcc`, links the resulting object file into the Fix program `fix_src`, and
/// runs it, failing the test unless it exits with code 0. `test_name` names the intermediate C and
/// object files, so each test that calls this needs a name of its own.
pub fn test_source_with_c(fix_src: &str, c_src: &str, test_name: &str) {
    // Create a working directory.
    let _ = fs::create_dir_all(COMPILER_TEST_WORKING_PATH);

    // Save `c_source` to a file.
    let c_file_path = format!("{}/{}.c", COMPILER_TEST_WORKING_PATH, test_name);
    let mut file = File::create(&c_file_path).unwrap();
    file.write_all(c_src.as_bytes()).unwrap();

    // Build `c_source` into an object file.
    let o_file_path = format!("{}/{}.o", COMPILER_TEST_WORKING_PATH, test_name);
    let mut command = Command::new("gcc");
    let output = command
        .arg("-c")
        .arg("-o")
        .arg(&o_file_path)
        .arg(&c_file_path)
        .output()
        .expect("Failed to run gcc.");
    if output.stderr.len() > 0 {
        eprintln!(
            "{}",
            String::from_utf8(output.stderr)
                .unwrap_or("(failed to parse stderr from gcc as UTF8.)".to_string())
        );
    }

    // Link the object file to the Fix program.
    let mut config = Configuration::develop_mode();
    config.object_files.push(PathBuf::from(&o_file_path));

    // Run the Fix program.
    test_source(&fix_src, config);

    // Remove the object file.
    let _ = fs::remove_file(o_file_path);
}

/// Copies the directory `src` into `dst`, recursing into subdirectories and creating `dst` and its
/// subdirectories as needed.
pub fn copy_dir_recursive(src: &PathBuf, dst: &PathBuf) -> io::Result<()> {
    fs::create_dir_all(dst)?;
    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let file_type = entry.file_type()?;
        let src_path = entry.path();
        let dst_path = dst.join(entry.file_name());

        if file_type.is_dir() {
            copy_dir_recursive(&src_path, &dst_path)?;
        } else {
            fs::copy(&src_path, &dst_path)?;
        }
    }
    Ok(())
}
