[[projects]]
name = "asynctask"
git = "https://github.com/tttmmmyyyy/fixlang-asynctask.git"

[[projects]]
name = "character"
git = "https://github.com/tttmmmyyyy/fixlang-character.git"

[[projects]]
name = "hash"
git = "https://github.com/tttmmmyyyy/fixlang-hash.git"

[[projects]]
name = "hashmap"
git = "https://github.com/tttmmmyyyy/fixlang-hashmap.git"

[[projects]]
name = "hashset"
git = "https://github.com/tttmmmyyyy/fixlang-hashset.git"

[[projects]]
name = "math"
git = "https://github.com/tttmmmyyyy/fixlang-math.git"

[[projects]]
name = "random"
git = "https://github.com/tttmmmyyyy/fixlang-random.git"

[[projects]]
name = "regexp"
git = "https://github.com/tttmmmyyyy/fixlang-regexp.git"

[[projects]]
name = "subprocess"
git = "https://github.com/tttmmmyyyy/fixlang-subprocess.git"

[[projects]]
name = "time"
git = "https://github.com/tttmmmyyyy/fixlang-time.git"

[[projects]]
name = "binary-heap"
git = "https://github.com/tttmmmyyyy/fixlang-binary-heap.git"

[[projects]]
name = "fast-iter"
git = "https://github.com/tttmmmyyyy/fixlang-fast-iter.git"
