use serde::{Deserialize, Serialize};

use super::*;

#[derive(Clone, Serialize, Deserialize)]
pub enum LLVMGenerator {
    IntLit(InlineLLVMIntLit),
    FloatLit(InlineLLVMFloatLit),
    NullPtrLit(InlineLLVMNullPtrLit),
    BoolLit(InlineLLVMBoolLit),
    StringLit(InlineLLVMStringLit),
    FixBody(InlineLLVMFixBody),
    CastIntegralBody(InlineLLVMCastIntegralBody),
    CastFloatBody(InlineLLVMCastFloatBody),
    CastIntToFloatBody(InlineLLVMCastIntToFloatBody),
    CastFloatToIntBody(InlineLLVMCastFloatToIntBody),
    ShiftBody(InlineLLVMShiftBody),
    BitwiseOperationBody(InlineLLVMBitwiseOperationBody),
    FillArrayBody(InlineLLVMFillArrayBody),
    MakeEmptyArrayBody(InlineLLVMMakeEmptyArrayBody),
    UnsafeSetArrayBody(InlineLLVMUnsafeSetArrayBody),
    UnsafeGetArrayBody(InlineLLVMUnsafeGetArrayBody),
    UnsafeSetSizeArrayBody(InlineLLVMUnsafeSetSizeArrayBody),
    ArrayGetBody(InlineLLVMArrayGetBody),
    ArraySetBody(InlineLLVMArraySetBody),
    ArrayModBody(InlineLLVMArrayModBody),
    ArrayForceUniqueBody(InlineLLVMArrayForceUniqueBody),
    ArrayGetPtrBody(InlineLLVMArrayGetPtrBody),
    ArrayGetSizeBody(InlineLLVMArrayGetSizeBody),
    ArrayGetCapacityBody(InlineLLVMArrayGetCapacityBody),
    StructGetBody(InlineLLVMStructGetBody),
    StructModBody(InlineLLVMStructModBody),
    StructSetBody(InlineLLVMStructSetBody),
    MakeUnionBody(InlineLLVMMakeUnionBody),
    UnionAsBody(InlineLLVMUnionAsBody),
    UnionIsBody(InlineLLVMUnionIsBody),
    UnionModBody(InlineLLVMUnionModBody),
    LoopFunctionBody(InlineLLVMLoopFunctionBody),
    AbortFunctionBody(InlineLLVMAbortFunctionBody),
    IsUniqueFunctionBody(InlineLLVMIsUniqueFunctionBody),
    IntNegBody(InlineLLVMIntNegBody),
    FloatNegBody(InlineLLVMFloatNegBody),
    BoolNegBody(InlineLLVMBoolNegBody),
    IntEqBody(InlineLLVMIntEqBody),
    PtrEqBody(InlineLLVMPtrEqBody),
    FloatEqBody(InlineLLVMFloatEqBody),
    IntLessThanBody(InlineLLVMIntLessThanBody),
    FloatLessThanBody(InlineLLVMFloatLessThanBody),
    IntLessThanOrEqBody(InlineLLVMIntLessThanOrEqBody),
    FloatLessThanOrEqBody(InlineLLVMFloatLessThanOrEqBody),
    IntAddBody(InlineLLVMIntAddBody),
    FloatAddBody(InlineLLVMFloatAddBody),
    IntSubBody(InlineLLVMIntSubBody),
    FloatSubBody(InlineLLVMFloatSubBody),
    IntMulBody(InlineLLVMIntMulBody),
    FloatMulBody(InlineLLVMFloatMulBody),
    IntDivBody(InlineLLVMIntDivBody),
    FloatDivBody(InlineLLVMFloatDivBody),
    IntRemBody(InlineLLVMIntRemBody),
    GetPtrOfBoxedValueFunctionBody(InlineLLVMGetPtrOfBoxedValueFunctionBody),
    MarkThreadedFunctionBody(InlineLLVMMarkThreadedFunctionBody),
    // AsyncTaskMakeTaskData(InlineLLVMAsyncTaskMakeTaskData),
    // AsyncTaskDeleteTaskData(InlineLLVMAsyncTaskDeleteTaskData),
}

impl LLVMGenerator {
    pub fn generate<'c, 'm, 'b>(
        &self,
        gc: &mut GenerationContext<'c, 'm>,
        ty: &Rc<TypeNode>,
        rvo: Option<Object<'c>>,
        rsv: &Vec<FullName>,
    ) -> Object<'c> {
        match self {
            LLVMGenerator::IntLit(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::FloatLit(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::NullPtrLit(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::BoolLit(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::StringLit(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::FixBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::CastIntegralBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::CastFloatBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::CastIntToFloatBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::CastFloatToIntBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::ShiftBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::BitwiseOperationBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::FillArrayBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::MakeEmptyArrayBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::UnsafeSetArrayBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::UnsafeGetArrayBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::UnsafeSetSizeArrayBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::ArrayGetBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::ArraySetBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::ArrayModBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::ArrayForceUniqueBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::ArrayGetPtrBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::ArrayGetSizeBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::ArrayGetCapacityBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::StructGetBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::StructModBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::StructSetBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::MakeUnionBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::UnionAsBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::UnionIsBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::UnionModBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::LoopFunctionBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::AbortFunctionBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::IsUniqueFunctionBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::IntNegBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::FloatNegBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::BoolNegBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::IntEqBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::PtrEqBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::FloatEqBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::IntLessThanBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::FloatLessThanBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::IntLessThanOrEqBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::FloatLessThanOrEqBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::IntAddBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::FloatAddBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::IntSubBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::FloatSubBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::IntMulBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::FloatMulBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::IntDivBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::FloatDivBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::IntRemBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::GetPtrOfBoxedValueFunctionBody(x) => x.generate(gc, ty, rvo, rsv),
            LLVMGenerator::MarkThreadedFunctionBody(x) => x.generate(gc, ty, rvo, rsv),
        }
    }

    // Returns a list of variables which is released by this generator.
    // None if the generator does not support this interface.
    // This is used for the borrowing optimization.
    pub fn released_vars(&self) -> Option<Vec<FullName>> {
        match self {
            LLVMGenerator::ArrayGetBody(x) => Some(x.released_vars()),
            _ => None,
        }
    }
}

#[derive(Clone, Serialize, Deserialize)]
pub struct InlineLLVM {
    pub generator: LLVMGenerator,
    pub free_vars: Vec<FullName>, // e.g. "+" literal has two free variables.
    // Set of variables which is contained in the list `released_vars()` but should not be released.
    pub borrowed_vars: Vec<FullName>,
    pub name: String,
    pub ty: Rc<TypeNode>,
}
