use super::{
    capture_struct::{fresh_global_name, CaptureStruct},
    find_usage_of_name::{self, UsageType},
    uncurry::internalize_let_to_var_at_head,
    unique_local_names,
};
use crate::graph::Graph;
use crate::{
    ast::{
        expr::{
            expr_abs_typed, expr_app_typed, expr_let_typed, expr_var, var_local, var_var, ExprNode,
        },
        name::FullName,
        pattern::PatternNode,
        program::{Program, Symbol},
        traverse::{EndVisitResult, ExprVisitor, StartVisitResult, VisitState},
        types::{type_fun, TyCon, TyConInfo, TypeNode},
    },
    constants::{
        CAP_NAME, CLOSURE_CALL_LAM_SUFFIX, CLOSURE_CAP_NAME, CLOSURE_LAM_SUFFIX,
        CLOSURE_SPEC_SUFFIX,
    },
    misc::{Map, Set},
    optimization::{pull_let, rename::rename_free_names},
    tool::stopwatch::StopWatch,
};
use std::{cell::RefCell, collections::VecDeque, mem, rc::Rc, sync::Arc};

/*
# Closure specialization

## Overview

This pass makes a lambda cheaper to call, by two techniques that feed each other. **Decapturing**
lifts a lambda to a global function taking its captured environment as an argument, which leaves a
plain value where a closure was. **Specialization** then copies a global function that receives such
a value, one copy per lifted lambda it is given, so the copy calls that lambda by name.

### Decapturing

For each lambda expression, a structure is defined that summarizes the values captured by that lambda expression.
And the lambda expression is defined as a global function.

For example, consider the following lambda expression:
```
let f = |x| x + n;
```

Then, the following structure and global function are defined. The names below are written short
for reading; see "The names this pass mints" for the shape they really take.
```
type #Cap = unbox struct { n: I64 };

#lam : #Cap -> I64 -> I64;
#lam = |{ n : n }, x| x + n;
```

The creation of the lambda value is replaced with `#Cap { n : n }`.
```
let f = #Cap { n : n };
```

### Rewriting the usage of the lambda

The call of the decaptured lambda expression `f(x)` is transformed into the following code.
```
#lam(f, x)
```

In principle, `f` is replaced with `#lam(f)` in places where `f` appears alone (i.e., not in a call expression).
However, in cases where specialization can be applied, `f` is left as is.

### Specializing a function on the lambda it is given

Consider the case where a lambda is given as an argument to a global function.
As an example, consider the case where `f` is passed as the second argument to `fold`.

```
fold : S -> (A -> S -> S) -> Iter -> S;
fold = |s, op, iter| (
    match iter.advance {
        none() => s,
        some((iter, a)) => iter.fold(op(a, s), op)
    }
);
```

```
it.fold(s0, f)
```

In this case, the following code is generated.

```
fold#spec : S -> #Cap -> Iter -> S;
fold#spec = |s, op, iter| (
    match iter.advance {
        none() => s,
        some((iter, a)) => iter.fold#spec(#lam(op, a, s), op)
    }
);
```

```
it.fold#spec(s0, f)
```

## Applicable range and limitations

### The path from defining a lambda to using it

If a lambda is defined and used as is, decapturing is applied.
Example: `iter.fold(s0, |acm, i| acm + i)`

If a lambda is defined in the right-hand side of a let statement and its name is used, decapturing is applied.
Example: `let f = |acm, i| acm + i; iter.fold(s0, f)`

However, if the path from defining a lambda to using it is more complex than this, decapturing is not applied.
Example: `let (_, f) = (0, |acm, i| acm + i); iter.fold(s0, f)`

## The names this pass mints

The names carry one `#closure` stem, so that a dump says which pass produced them:

* `<symbol>#closure_lam<n>` — the global function a decaptured lambda becomes.
* `<symbol>#closure_spec_<hash>` — the copy of a global function specialized on the lambdas passed
  to it, where the hash stands for which argument received which decaptured lambda.
* `<local>#closure_call_lam` — a local binding. Where an inline-LLVM expression reads a variable
  holding a decaptured lambda's capture list, the call of that lambda is bound to a local of this
  name and the expression reads that instead.
* `CLOSURE_CAP_NAME` — the parameter a decaptured lambda receives its capture list through.

The capture struct's type constructor is named by `CaptureStruct`, which this pass gives the prefix
`#CapList` and `defunctionalize_fix` gives `#FixCap`: those two are chosen together at that
constructor and read against each other, so they sit outside this stem.

## Relations to other optimizations

* We perform `pull-let` transformation before decapturing.
* Inline expansion should be performed before this optimization. For example, the expression `f >> g` is replaced with a lambda expression by inline expansion, making it a target of this optimization.
* It may be worth performing inline expansion after this optimization. This is because global functions are generated by this optimization, and inline expansion may be performed on them.
* It may be worth performing inline expansion before this optimization. This is because the number of arguments that can be specialized increases due to eta expansion.
* To improve the performance of global functions generated by this optimization, uncurrying should be performed after this optimization.
*/

// A way into a function, which is what a specialization is keyed on. Decapturing leaves a value two
// ways of reaching a function's body: as an argument, or as a field of the capture list a lifted
// lambda receives. A path one field deep therefore covers both, and covering no more is what keeps
// the set of specializations a program can ask for finite.
#[derive(Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Debug)]
struct Slot {
    // Which argument the value arrives through.
    arg: usize,
    // `None` for the argument itself; `Some(j)` for the j-th field of the capture list it carries.
    field: Option<usize>,
}

impl Slot {
    fn arg(arg: usize) -> Self {
        Slot { arg, field: None }
    }

    // How the slot reads in a specialized function's name, and so in the hash that name carries.
    fn to_string(&self) -> String {
        match self.field {
            None => format!("{}", self.arg),
            Some(field) => format!("{}.{}", self.arg, field),
        }
    }
}

// A closure value whose identity is known: which lambda it is, and which of the fields of the
// capture list it carries are themselves known.
//
// This is what a specialization is keyed on, and what the type constructor of a capture list is
// named after, so that a value of that type says what to call it with.
#[derive(Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Debug)]
struct Tree {
    // The lambda decapturing lifted, which is what a call through this value reaches.
    lambda: FullName,
    // The capture fields whose own identity is known, by position, in ascending order.
    fields: Vec<(usize, Tree)>,
}

impl Tree {
    // The value of a lambda whose capture fields are all still closures.
    fn leaf(lambda: FullName) -> Self {
        Tree {
            lambda,
            fields: Vec::new(),
        }
    }

    // How the tree reads in a name, and so in the hash that name carries.
    fn to_string(&self) -> String {
        let mut text = self.lambda.to_string();
        for (field, tree) in &self.fields {
            text += &format!("|{}:{}", field, tree.to_string());
        }
        text
    }

    // The unit that receives a value of this tree: the lambda, with its known capture fields
    // substituted.
    fn unit(&self) -> UnitKey {
        UnitKey {
            origin: self.lambda.clone(),
            subst: self
                .fields
                .iter()
                .map(|(field, tree)| {
                    (
                        Slot {
                            arg: 0,
                            field: Some(*field),
                        },
                        tree.clone(),
                    )
                })
                .collect(),
        }
    }
}

// One copy of a function: the function it copies, and what each of its slots is known to receive.
// An empty substitution names the function itself.
#[derive(Clone, PartialEq, Eq, Hash, Debug)]
struct UnitKey {
    origin: FullName,
    // Slots in ascending order, so that the name below is a function of the key alone.
    subst: Vec<(Slot, Tree)>,
}

impl UnitKey {
    fn name(&self) -> FullName {
        if self.subst.is_empty() {
            return self.origin.clone();
        }
        let mut full_name = self.origin.clone();
        let name = full_name.name_as_mut();
        *name += CLOSURE_SPEC_SUFFIX;
        let mut hash_data = String::new();
        for (slot, tree) in &self.subst {
            hash_data += &format!(",{},{}", slot.to_string(), tree.to_string());
        }
        *name += &format!("_{:x}", md5::compute(hash_data));
        full_name
    }
}

// The capture struct a value of `tree` is: the lifted lambda's, with each known field narrowed to
// the capture struct of what it holds. The type constructor is named after the unit that receives
// it, so the type and the tree determine each other.
fn capture_struct_of(tree: &Tree, lifted: &Map<FullName, DecapturedLambdaInfo>) -> CaptureStruct {
    let mut cap = lifted
        .get(&tree.lambda)
        .unwrap_or_else(|| panic!("no lifted lambda named {}", tree.lambda.to_string()))
        .cap
        .clone();
    for (field, inner) in &tree.fields {
        cap = cap.with_field_type(
            CAP_LIST_PREFIX,
            &tree.unit().name(),
            *field,
            capture_struct_of(inner, lifted).ty,
        );
    }
    cap
}

// What a specialized copy is a copy of, followed to the root: `L` specialized on some slot, and
// that copy specialized again, both have origin `L`. A function absent from the map is its own
// origin, which covers everything the program was written with and every lifted lambda.
type Origins = Map<FullName, FullName>;

fn origin_of(origins: &Origins, name: &FullName) -> FullName {
    origins.get(name).cloned().unwrap_or_else(|| name.clone())
}

// What a chain of specializations has committed to, keyed by
// `(origin of the function, slot, origin of the lambda)`. The value is the one lifted lambda that
// key may be specialized on: meeting the same key with a different lambda is what stops a recursion
// that wraps its closure argument on every round from asking for a copy per round. Every
// specialized copy carries the table of the request that created it, so the outer loop walking that
// copy again continues the same chain rather than starting a fresh one.
type Pinned = Map<(FullName, Slot, FullName), FullName>;

// Run the optimization over `prg`, in three phases.
//
// Lifting runs to completion first, so that the set of functions a specialization can be keyed on is
// settled before anything is keyed on it. The table of what is worth specializing is then solved
// once over the program lifting left behind. Only then are copies made, from that same program, so
// that a copy's body names the functions the table answers for.
pub fn run(prg: &mut Program, show_build_times: bool) {
    let _sw = StopWatch::new("closure_specialization::run", show_build_times);

    let lifted = Rc::new(RefCell::new(Map::default()));
    lift_all(prg, &lifted, show_build_times);

    let specializable_funcs = Rc::new(specializable_functions(&prg.symbols));
    realize_all(prg, &lifted, specializable_funcs, show_build_times);
}

// Lift every lambda in the program to a global function, until lifting one leaves nothing more to
// lift. A lambda lifted here is a global function of its own, which the next pass over the symbols
// walks in turn.
fn lift_all(
    prg: &mut Program,
    lifted: &Rc<RefCell<Map<FullName, DecapturedLambdaInfo>>>,
    show_build_times: bool,
) {
    let _sw = StopWatch::new("closure_specialization::lift_all", show_build_times);

    // Nothing is specializable during this phase, so the walk only lifts: a value whose identity is
    // known is wrapped back into a closure wherever it is used, and no request is raised.
    let nothing_specializable = Rc::new(Map::default());
    let mut stable = Set::default();

    loop {
        let mut changed = false;
        let symbols = mem::take(&mut prg.symbols);
        let mut new_symbols: Map<FullName, Symbol> = Map::default();
        let mut new_tycons = Map::default();
        let mut global_names = symbols.keys().cloned().collect::<Set<_>>();

        for (name, mut sym) in symbols {
            if stable.contains(&name) {
                new_symbols.insert(name, sym);
                continue;
            }
            let mut visitor = ClosureSpecializationVisitor::new(
                name.clone(),
                nothing_specializable.clone(),
                lifted.clone(),
                global_names.clone(),
                Rc::new(Origins::default()),
                Pinned::default(),
            );
            let expr = pull_let::run_on_expr(sym.expr.as_ref().unwrap()); // Increase the number of places decapturing applies to.
            let expr = unique_local_names::run_on_expr(&expr, Set::default()); // Preconditions for decapturing.
            let trav_res = visitor.traverse(&expr);
            if !trav_res.changed {
                stable.insert(name.clone());
                new_symbols.insert(name, sym);
                continue;
            }
            changed = true;
            sym.expr = Some(trav_res.expr);
            register_decaptured_lambdas(
                visitor.decap_lambdas,
                &mut new_symbols,
                &mut global_names,
                &mut new_tycons,
            );
            new_symbols.insert(name, sym);
        }

        prg.type_env.add_tycons(new_tycons);
        prg.symbols = new_symbols;
        if !changed {
            return;
        }
    }
}

// Make every copy the program asks for, starting from the functions themselves.
//
// The bodies every copy is made from are the ones lifting left behind, so a copy names the same
// functions its original does and the table answers for all of them.
fn realize_all(
    prg: &mut Program,
    lifted: &Rc<RefCell<Map<FullName, DecapturedLambdaInfo>>>,
    specializable_funcs: Rc<Map<FullName, SpecializableFunctionInfo>>,
    show_build_times: bool,
) {
    let _sw = StopWatch::new("closure_specialization::realize_all", show_build_times);

    let bodies = mem::take(&mut prg.symbols);
    let mut global_names = bodies.keys().cloned().collect::<Set<_>>();
    let mut new_tycons = Map::default();
    let mut symbols: Map<FullName, Symbol> = Map::default();
    let mut origins = Origins::default();

    // Every function stands for the copy of itself that substitutes nothing.
    let mut queue = bodies
        .keys()
        .map(|origin| SpecializationRequest {
            org_func_name: origin.clone(),
            org_func_ty: bodies[origin].ty.clone(),
            specialized_args: Map::default(),
            pinned: Pinned::default(),
        })
        .collect::<VecDeque<_>>();

    while let Some(request) = queue.pop_front() {
        let name = request.specialized_func_name();
        if symbols.contains_key(&name) {
            continue;
        }
        let org = &bodies[&request.org_func_name];
        let expr = unique_local_names::run_on_expr(org.expr.as_ref().unwrap(), Set::default());

        // Tell the walk what each substituted slot holds, by the local name it arrives under.
        let mut local_decap_lambdas = Map::default();
        let (args, _) = expr.destructure_lam_sequence();
        for (slot, tree) in &request.specialized_args {
            assert!(slot.field.is_none());
            assert!(slot.arg < args.len());
            assert_eq!(args[slot.arg].len(), 1);
            let name = args[slot.arg][0].name.clone();
            let cap_list_ty = capture_struct_of(tree, &lifted.borrow()).ty;
            local_decap_lambdas.insert(
                name.clone(),
                Known {
                    tree: tree.clone(),
                    cap_list: expr_var(name, None).set_type(cap_list_ty),
                },
            );
        }

        origins.insert(name.clone(), request.org_func_name.clone());
        let mut visitor = ClosureSpecializationVisitor::new(
            name.clone(),
            specializable_funcs.clone(),
            lifted.clone(),
            global_names.clone(),
            Rc::new(origins.clone()),
            request.pinned.clone(),
        );
        visitor.local_decap_lambdas = local_decap_lambdas;
        let trav_res = visitor.traverse(&expr);

        let ty = if request.specialized_args.is_empty() {
            org.ty.clone()
        } else {
            request.specialized_func_ty(&lifted.borrow())
        };
        symbols.insert(
            name.clone(),
            Symbol {
                name: name.clone(),
                generic_name: request.org_func_name.clone(),
                ty,
                expr: Some(trav_res.expr),
            },
        );
        global_names.insert(name);
        register_decaptured_lambdas(
            visitor.decap_lambdas,
            &mut symbols,
            &mut global_names,
            &mut new_tycons,
        );
        queue.extend(visitor.required_specializations);
    }

    prg.type_env.add_tycons(new_tycons);
    prg.symbols = symbols;
}

// Register the global function each decaptured lambda became into `symbols` and `global_names`, and
// the type constructor of its capture list into `new_tycons`.
fn register_decaptured_lambdas(
    decap_lambdas: Vec<DecapturedLambdaInfo>,
    symbols: &mut Map<FullName, Symbol>,
    global_names: &mut Set<FullName>,
    new_tycons: &mut Map<TyCon, TyConInfo>,
) {
    for decap_lam in decap_lambdas {
        let decap_lam_sym = decap_lam.make_symbol();
        global_names.insert(decap_lam_sym.name.clone());
        symbols.insert(decap_lam_sym.name.clone(), decap_lam_sym);
        new_tycons.insert(
            decap_lam.cap.tycon.as_ref().clone(),
            decap_lam.cap.tycon_info,
        );
    }
}

// Compute the set of specializable functions.
//
// More precisely, it calculates whether a certain parameter of a function is specializable or not.
//
// Specialization can cause infinite loops.
// For example, suppose a function `f` takes a closure `p` as its first parameter. `f` creates a new closure `q` that captures `p` and calls `f(q)`.
// In this case, if the parameter `p` of `f` is specialized, it will require an infinite number of specializations for different types.
//
// To avoid infinite loops, we only specialize a parameter `p` of a function `f` that satisfies the following conditions:
// - If `f` calls a function `g` other than itself, there should not be a path from `g` to `f` in the call graph.
// - Assume that `p` is the i-th index of `f`. The call to `f` in `f` must also pass `p` as the i-th index.
//
// This is only a sufficient condition to avoid infinite loops. More generally, we should solve the following problem:
// Consider a graph consisting of all parameters (of function type) of all functions.
// In other words, each node is a pair `(f, p)` where `f` is a function and `p` is a parameter that has a function type.
// An edge from `(f, p)` to `(g, q)` exists if `f` calls `g`, and the expression given to parameter `q` directly or indirectly captures lambda `p`.
// Finally, assign a weight of 0 or 1 to the edge: if the capture list types of `p` and `q` are the same, the weight is 0; otherwise, it is 1.
//
// If there is a cycle with positive cost in this graph, an infinite loop will occur.
// Choosing specializable arguments is equivalent to removing some nodes from this graph so that there is no cycle with positive cost.
// This is a more difficult problem than the Feedback Vertex Set problem, so we need to rely on heuristics.
//
// Finally, even if a parameter is a specializable, if it is not worth specializing or the inline cost of the function is high, it is returned as impossible to specialize.
fn specializable_functions(
    symbols: &Map<FullName, Symbol>,
) -> Map<FullName, SpecializableFunctionInfo> {
    let call_graph = call_graph_of(symbols);
    let call_graph_scc = call_graph.compute_sccs();
    let name_to_idx = (0..call_graph.len())
        .map(|idx| (call_graph.get(idx).clone(), idx))
        .collect::<Map<FullName, usize>>();

    // Callers of each function, which is who has to be judged again once it enters the table. A
    // callee absent from `symbols` is a specialization whose body is not made yet, and nothing
    // reads its slots until it is.
    let mut callers = vec![Vec::<usize>::new(); call_graph.len()];
    for (caller, sym) in symbols {
        let caller_idx = name_to_idx[caller];
        for callee in sym.expr.as_ref().unwrap().free_vars() {
            if let Some(callee_idx) = name_to_idx.get(&callee) {
                callers[*callee_idx].push(caller_idx);
            }
        }
    }

    // Whether a parameter is specializable is defined in terms of the table being built: a
    // parameter forwarded to a specializable parameter of another function is specializable in
    // turn. Growing the table can only make more parameters qualify, so starting from the empty
    // table and adding what qualifies reaches the least fixed point.
    //
    // Seeding the queue callees-first means most functions are judged once, since what they
    // forward to has settled by the time they come up.
    let mut order = (0..call_graph.len()).collect::<Vec<_>>();
    order.sort_by(|a, b| call_graph_scc[*b].cmp(&call_graph_scc[*a]));
    let mut queue = order.into_iter().collect::<VecDeque<_>>();
    let mut queued = vec![true; call_graph.len()];

    let mut specializable_funcs: Map<FullName, SpecializableFunctionInfo> = Map::default();
    while let Some(idx) = queue.pop_front() {
        queued[idx] = false;
        let sym_name = call_graph.get(idx);
        let sym = symbols.get(sym_name).unwrap();
        let specializable_slots = specializable_slots_of(sym, &specializable_funcs);
        if specializable_slots.is_empty() {
            continue;
        }
        let settled = specializable_funcs
            .get(sym_name)
            .is_some_and(|info| info.specializable_slots == specializable_slots);
        if settled {
            continue;
        }
        specializable_funcs.insert(
            sym_name.clone(),
            SpecializableFunctionInfo {
                specializable_slots,
            },
        );
        for caller_idx in &callers[idx] {
            if !queued[*caller_idx] {
                queued[*caller_idx] = true;
                queue.push_back(*caller_idx);
            }
        }
    }
    specializable_funcs
}

// Whether a value arriving under `name` inside `body` is reached without an indirect call: it is
// either called there, or handed to a slot of another function that is itself specializable. That
// is what a specialized copy gains — the call becomes direct, or the function downstream gets a
// known lambda and specializes in turn — so the size of the function holding it does not enter the
// judgement.
fn reaches_a_direct_call(
    name: &FullName,
    body: &Arc<ExprNode>,
    specializable_funcs: &Map<FullName, SpecializableFunctionInfo>,
) -> bool {
    find_usage_of_name::run(body, name)
        .into_iter()
        .any(|usage| match usage {
            UsageType::CalledAsFunction => true,
            UsageType::FunctionArgument(fun, idx) => specializable_funcs
                .get(&fun)
                .is_some_and(|info| info.specializable_slots.contains(&Slot::arg(idx))),
            // Reaching a capture list is what the capture slots are for, which nothing raises yet.
            UsageType::CapturedInto(_, _) => false,
        })
}

// The slots of `sym` a specialized copy is worth making for, judged against the table of
// specializable functions as it stands. Adding entries to `specializable_funcs` can only add slots
// here, never remove one.
fn specializable_slots_of(
    sym: &Symbol,
    specializable_funcs: &Map<FullName, SpecializableFunctionInfo>,
) -> Set<Slot> {
    let expr = sym.expr.as_ref().unwrap();

    // Check if each parameter of `sym` is specializable.
    let (params, body) = expr.destructure_lam_sequence();
    let params = params
        .iter()
        .map(|may_multi_param| {
            assert_eq!(may_multi_param.len(), 1);
            may_multi_param[0].name.clone()
        })
        .collect::<Vec<_>>();
    let param_tys = sym.ty.collect_app_src(usize::MAX).0;
    let mut specializable_slots = Set::default();
    for param_idx in 0..params.len() {
        // A parameter shadowed by a later one is never the one in scope where the body uses that
        // name, so nothing arrives through it.
        let param_name = &params[param_idx];
        if params[param_idx + 1..]
            .iter()
            .any(|name| name == param_name)
        {
            continue;
        }

        // A specializable argument must have a type of function.
        if param_tys[param_idx].is_closure() {
            if reaches_a_direct_call(param_name, &body, specializable_funcs) {
                specializable_slots.insert(Slot::arg(param_idx));
            }
            continue;
        }
    }
    specializable_slots
}

// The call graph of `symbols`: an edge from A to B means A calls B.
//
// A call site is rewritten to name a specialized function before that function's body is made, so
// a callee absent from `symbols` is one about to be created and carries no edge yet.
fn call_graph_of(symbols: &Map<FullName, Symbol>) -> Graph<FullName> {
    let names = symbols.keys().cloned().collect::<Vec<_>>();
    let idx_of = names
        .iter()
        .enumerate()
        .map(|(idx, name)| (name.clone(), idx))
        .collect::<Map<FullName, usize>>();
    let mut graph = Graph::new(names);
    for (caller, sym) in symbols {
        for callee in sym.expr.as_ref().unwrap().free_vars() {
            if let Some(callee_idx) = idx_of.get(&callee) {
                graph.connect_idx(idx_of[caller], *callee_idx);
            }
        }
    }
    graph
}

// The visitor that lifts a symbol's lambdas and records the specializations they enable.
struct ClosureSpecializationVisitor {
    /* Decapturing */
    // Information of decaptured lambdas generated by this optimization
    decap_lambdas: Vec<DecapturedLambdaInfo>,
    // When a value whose identity is known is given a local name, it is stored here.
    local_decap_lambdas: Map<FullName, Known>,
    // Every lambda decapturing has lifted, which is what a tree is read against. A lambda lifted by
    // this walk is in here the moment it is made, so a tree naming it can be read at once.
    lifted: Rc<RefCell<Map<FullName, DecapturedLambdaInfo>>>,

    /* Specialization */
    // Specializable functions
    specializable_funcs: Rc<Map<FullName, SpecializableFunctionInfo>>,
    // Specialization requests generated by decapturing
    required_specializations: Vec<SpecializationRequest>,

    /* Fields related to name generation of lambda function */
    // Counter used to generate lambda function names
    lam_func_counter: u32,
    // Name of the symbol currently being optimized
    // Used to generate the names of lambda functions.
    current_symbol: FullName,
    // Set of global names
    // Used to avoid name collisions when generating new global names.
    global_names: Set<FullName>,

    /* Termination */
    // What each function generated so far is a copy of.
    origins: Rc<Origins>,
    // What the chain reaching the symbol being walked has committed to.
    pinned: Pinned,
}

// A local name whose value has a known identity, and where the bare capture list behind it can be
// read from.
//
// A name bound to the capture list itself gives that name; a name bound to the closure wrapped
// around one gives the expression inside the wrap. Reading the identity of a binding never rewrites
// it: a rewrite would leave the wrapping rules something to do again, and the two would take turns
// undoing each other.
#[derive(Clone)]
struct Known {
    tree: Tree,
    cap_list: Arc<ExprNode>,
}

impl Known {
    // Whether the name this was recorded against holds the capture list itself, rather than a
    // closure wrapped around one. Only such a name needs wrapping where a closure is called for.
    fn is_the_capture_list(&self, name: &FullName) -> bool {
        self.cap_list.is_var() && &self.cap_list.get_var().name == name
    }
}

impl ClosureSpecializationVisitor {
    // Create a new visitor
    fn new(
        current_symbol: FullName,
        specializable_funcs: Rc<Map<FullName, SpecializableFunctionInfo>>,
        lifted: Rc<RefCell<Map<FullName, DecapturedLambdaInfo>>>,
        global_names: Set<FullName>,
        origins: Rc<Origins>,
        pinned: Pinned,
    ) -> Self {
        ClosureSpecializationVisitor {
            decap_lambdas: Vec::new(),
            local_decap_lambdas: Map::default(),
            lifted,
            specializable_funcs,
            required_specializations: Vec::new(),
            lam_func_counter: 0,
            current_symbol,
            global_names,
            origins,
            pinned,
        }
    }

    // Commit the chain reaching here to specializing `slot` of the function whose origin is
    // `func_origin` on `lam_name`, and report whether it may be specialized on at all.
    //
    // It may not where the chain has already committed that key to a different lambda: that is a
    // recursion handing the next round a closure built from the one it was given, and following it
    // would ask for one copy per round.
    fn commit(
        &self,
        pinned: &mut Pinned,
        func_origin: &FullName,
        slot: Slot,
        lam_name: &FullName,
    ) -> bool {
        let key = (
            func_origin.clone(),
            slot,
            origin_of(&self.origins, lam_name),
        );
        match pinned.get(&key) {
            Some(committed) => committed == lam_name,
            None => {
                pinned.insert(key, lam_name.clone());
                true
            }
        }
    }

    // The capture struct a value of `tree` is.
    fn cap_of(&self, tree: &Tree) -> CaptureStruct {
        capture_struct_of(tree, &self.lifted.borrow())
    }

    // The function a value of `tree` is called through, as an expression, together with its type.
    // For a tree whose fields are all still closures this is the lifted lambda itself; otherwise it
    // is the copy that receives the narrowed capture list, whose body the second stage makes.
    fn lambda_func_of(&self, tree: &Tree) -> Arc<ExprNode> {
        let base = self.lifted.borrow()[&tree.lambda].lambda_func();
        let (mut doms, codom) = base.type_.as_ref().unwrap().collect_app_src(usize::MAX);
        doms[0] = self.cap_of(tree).ty;
        let mut ty = codom;
        for dom in doms.iter().rev() {
            ty = type_fun(dom.clone(), ty);
        }
        expr_var(tree.unit().name(), None).set_type(ty)
    }

    // The value `expr` carries, where its identity is known, together with the bare capture list it
    // is carried by.
    //
    // Identity arrives in two shapes: a local this walk was told about, and a capture list wrapped
    // back into a closure by the function that receives it, which is what lifting leaves behind
    // wherever it could not say more.
    fn known_value(&self, expr: &Arc<ExprNode>) -> Option<Known> {
        if expr.is_var() {
            return self.local_decap_lambdas.get(&expr.get_var().name).cloned();
        }
        if !expr.is_app() {
            return None;
        }
        let (func, args) = expr.destructure_app();
        if args.len() != 1 || !func.is_var() {
            return None;
        }
        let lambda = func.get_var().name.clone();
        if !self.lifted.borrow().contains_key(&lambda) {
            return None;
        }
        Some(Known {
            tree: Tree::leaf(lambda),
            cap_list: args[0].clone(),
        })
    }

    // Whether `expr` is a lambda whose captured environment can be read off it, so that it can be
    // lifted to a global function taking that environment as an argument. The free variables of an
    // expression leave `CAP_NAME` out, so a body that reads it captures more than this can see.
    fn decapturable(expr: &Arc<ExprNode>) -> bool {
        // If the expression is a not lambda expression, it is not decapturable.
        if !expr.is_lam() {
            return false;
        }

        let body = expr.get_lam_body();
        if body.has_free_var(&FullName::local(CAP_NAME)) {
            return false;
        }

        true
    }

    // Decapture a lambda expression.
    //
    // Returns `DecapturedLambdaInfo` and the expression that generates the capture list.
    fn decapture_lambda(
        &mut self,
        mut lam: Arc<ExprNode>,
        state: &mut VisitState,
    ) -> (Tree, Arc<ExprNode>) {
        // Get the capture list.
        let cap_names = lam.lambda_cap_names();

        // If the lambda captures a decaptured lambda, visit `lam` in advance to ensure that the decaptured lambda in `lam` is processed.
        for cap_name in &cap_names {
            if self.local_decap_lambdas.contains_key(cap_name) {
                let lam_visit_res = self.visit_expr(&lam, state);
                lam = self.revisit_if_changed(lam_visit_res, state).expr;
                break;
            }
        }

        // For each captured name, get its type.
        let cap_names_types = cap_names
            .iter()
            .map(|name| {
                let ty = state.scope.get_local(&name.name).unwrap().unwrap();
                (name.clone(), ty.clone())
            })
            .collect::<Vec<_>>();

        // Name the lifted function first: the capture list is named after it, so that a value of
        // that capture list says which function consumes it.
        let lambda_func_name = fresh_global_name(
            &self.current_symbol,
            CLOSURE_LAM_SUFFIX,
            &mut self.lam_func_counter,
            &mut self.global_names,
        );

        // Build the capture list struct that threads the captured environment into the lifted
        // function.
        let cap = CaptureStruct::new(CAP_LIST_PREFIX, &lambda_func_name, &cap_names_types);
        let cap_list_expr = cap.struct_expr();

        let decap_lam = DecapturedLambdaInfo::new(cap, lam, lambda_func_name.clone());
        self.decap_lambdas.push(decap_lam.clone());
        self.lifted
            .borrow_mut()
            .insert(lambda_func_name.clone(), decap_lam);
        (Tree::leaf(lambda_func_name), cap_list_expr)
    }
}

// Information of specializable functions
#[derive(Clone)]
struct SpecializableFunctionInfo {
    // The ways into this function a specialized copy is worth making for.
    specializable_slots: Set<Slot>,
}

// Information of specialization requests
struct SpecializationRequest {
    // Name of the function to be specialized
    org_func_name: FullName,
    // Type of the function to be specialized
    org_func_ty: Arc<TypeNode>,
    // Map from the slot specialized on to the value that reaches it
    specialized_args: Map<Slot, Tree>,
    // What the chain producing this request has committed to. The specialized function carries it
    // on, so the requests raised while walking its body are judged against the same chain.
    pinned: Pinned,
}

impl SpecializationRequest {
    // The unit this request asks for.
    fn unit(&self) -> UnitKey {
        let mut subst = self
            .specialized_args
            .iter()
            .map(|(slot, tree)| (*slot, tree.clone()))
            .collect::<Vec<_>>();
        subst.sort_by_key(|(slot, _)| *slot);
        UnitKey {
            origin: self.org_func_name.clone(),
            subst,
        }
    }

    // Generate the name of the specialized function.
    fn specialized_func_name(&self) -> FullName {
        self.unit().name()
    }

    // Create the type of the specialized function
    fn specialized_func_ty(&self, lifted: &Map<FullName, DecapturedLambdaInfo>) -> Arc<TypeNode> {
        // Decompose the function type `A1 -> A2 -> ... -> An -> B` into `([A1, A2, ..., An], B)`,
        // and replace the type of the specialized arguments with the type of the capture list.
        let org_ty = self.org_func_ty.clone();
        let (mut doms, codom) = org_ty.collect_app_src(usize::MAX);
        for (slot, tree) in self.unit().subst {
            assert!(slot.field.is_none());
            doms[slot.arg] = capture_struct_of(&tree, lifted).ty;
        }

        // Convert back to a function type
        let mut func_ty = codom;
        for dom in doms.iter().rev() {
            func_ty = type_fun(dom.clone(), func_ty);
        }

        func_ty
    }

    // Create an expression to refer to the specialized function.
    fn specialized_func_expr(&self, lifted: &Map<FullName, DecapturedLambdaInfo>) -> Arc<ExprNode> {
        expr_var(self.specialized_func_name(), None).set_type(self.specialized_func_ty(lifted))
    }
}

// The prefix of the type constructor naming a capture list this pass builds.
const CAP_LIST_PREFIX: &str = "#CapList";

// What a lambda expression became once decaptured: the capture list struct that threads its
// captured environment into a global function, the lambda itself, and the name that function goes
// by.
//
// The lambda is kept rather than only the function built around it, because specializing one of the
// capture slots means building that function again around a capture struct with the slot's type
// narrowed.
#[derive(Clone)]
struct DecapturedLambdaInfo {
    cap: CaptureStruct,
    lam: Arc<ExprNode>,
    lambda_func_name: FullName,
}

impl DecapturedLambdaInfo {
    // Wrap `lam` into the global function that receives its captured environment as an argument and
    // destructures it at the head of the body.
    fn new(cap: CaptureStruct, lam: Arc<ExprNode>, lambda_func_name: FullName) -> Self {
        DecapturedLambdaInfo {
            cap,
            lam,
            lambda_func_name,
        }
    }

    // The global function the lambda became.
    fn lambda_func(&self) -> Arc<ExprNode> {
        let body = expr_let_typed(
            self.cap.pattern(),
            expr_var(FullName::local(CLOSURE_CAP_NAME), None).set_type(self.cap.ty.clone()),
            self.lam.clone(),
        );
        let func = expr_abs_typed(var_local(CLOSURE_CAP_NAME), self.cap.ty.clone(), body);
        internalize_let_to_var_at_head(&func)
    }

    // Create a symbol for the lambda function generated by decapturing
    fn make_symbol(&self) -> Symbol {
        let lambda_func = self.lambda_func();
        Symbol {
            name: self.lambda_func_name.clone(),
            generic_name: self.lambda_func_name.clone(),
            ty: lambda_func.type_.as_ref().unwrap().clone(),
            expr: Some(lambda_func),
        }
    }
}

impl ExprVisitor for ClosureSpecializationVisitor {
    fn start_visit_var(
        &mut self,
        expr: &Arc<ExprNode>,
        _state: &mut VisitState,
    ) -> StartVisitResult {
        // If `expr` refers to a decaptured lambda, and
        // the type of this expression is T, and the lambda function type is C->T (C is the capture list type),
        // replace it with an expression that applies the lambda function to the capture list.

        // Get the name
        let name = &expr.get_var().name;

        // Check that the variable name is local.
        if !name.is_local() {
            return StartVisitResult::VisitChildren;
        }

        // Check if this name holds the capture list of a lambda this walk knows. A name bound to
        // the closure wrapped around one already has the type its uses call for.
        let decap_lambda = self.local_decap_lambdas.get(name).cloned();
        if decap_lambda.is_none() {
            return StartVisitResult::VisitChildren;
        }
        let decap_lambda = decap_lambda.unwrap();
        if !decap_lambda.is_the_capture_list(name) {
            return StartVisitResult::VisitChildren;
        }
        let decap_lambda = decap_lambda.tree;

        // If the required type for this expression is already the capture list type, do nothing.
        let expr_ty = expr.type_.as_ref().unwrap().clone();
        let cap_list_ty = self.cap_of(&decap_lambda).ty;
        if expr_ty.to_string() == cap_list_ty.to_string() {
            return StartVisitResult::VisitChildren;
        }

        // Check that the required type for this expression matches the codomain of the lambda function.
        let lam = self.lambda_func_of(&decap_lambda);
        let lambda_codom_ty = lam.type_.as_ref().unwrap().get_lambda_dst();
        assert_eq!(expr_ty.to_string(), lambda_codom_ty.to_string());

        // Replace with an expression that applies the lambda function to the capture list.
        let expr = expr_app_typed(lam, vec![expr.set_type(cap_list_ty)]);
        StartVisitResult::ReplaceAndRevisit(expr)
    }

    fn end_visit_var(&mut self, expr: &Arc<ExprNode>, _state: &mut VisitState) -> EndVisitResult {
        EndVisitResult::unchanged(expr)
    }

    fn start_visit_llvm(
        &mut self,
        llvm_expr: &Arc<ExprNode>,
        _state: &mut VisitState,
    ) -> StartVisitResult {
        // If any free variable in the LLVM expression refers to a decaptured lambda,
        // replace it with an expression that applies the lambda function to the capture list.

        let mut replace = Map::default(); // Data for replacing free variables in the LLVM expression
        for free_name in llvm_expr.free_vars() {
            let opt_decap_lambda = self.local_decap_lambdas.get(&free_name).cloned();
            if opt_decap_lambda.is_none() {
                continue;
            }
            let decap_lambda = opt_decap_lambda.unwrap();
            if !decap_lambda.is_the_capture_list(&free_name) {
                continue;
            }
            let decap_lambda = decap_lambda.tree;

            // Create an expression that applies the lambda function to the capture list.
            let lam = self.lambda_func_of(&decap_lambda);
            let name_expr =
                expr_var(free_name.clone(), None).set_type(self.cap_of(&decap_lambda).ty);
            let expr = expr_app_typed(lam, vec![name_expr]);

            replace.insert(free_name.clone(), expr);
        }

        // If none of the free variables in the LLVM expression refer to a decaptured lambda, do nothing.
        if replace.is_empty() {
            return StartVisitResult::VisitChildren;
        }

        let make_new_name = |name: &FullName| {
            let mut new_name = name.clone();
            new_name.name_as_mut().push_str(CLOSURE_CALL_LAM_SUFFIX);
            new_name
        };

        // Rename free variables in the LLVM expression
        let mut llvm_expr = llvm_expr.clone();
        let mut rename: Map<FullName, FullName> = Default::default();
        for (name, _) in replace.iter() {
            rename.insert(name.clone(), make_new_name(name));
        }
        llvm_expr = rename_free_names(&llvm_expr, rename);

        // Insert `let (new name) = (lambda function call);` before the LLVM expression
        let mut expr = llvm_expr.clone();
        for (name, call_lam_expr) in replace.iter() {
            let new_name = make_new_name(name);
            expr = expr_let_typed(
                PatternNode::make_var(var_var(new_name.clone()), None)
                    .set_type(call_lam_expr.type_.as_ref().unwrap().clone()),
                call_lam_expr.clone(),
                expr.clone(),
            );
        }

        StartVisitResult::ReplaceAndRevisit(expr)
    }

    fn end_visit_llvm(&mut self, expr: &Arc<ExprNode>, _state: &mut VisitState) -> EndVisitResult {
        EndVisitResult::unchanged(expr)
    }

    // Specialize the called function when it is a specializable global and a specializable argument
    // is either a lambda expression or an already decaptured lambda (i.e., a capture list).
    fn start_visit_app(
        &mut self,
        expr: &Arc<ExprNode>,
        state: &mut VisitState,
    ) -> StartVisitResult {
        let (func, args) = expr.destructure_app();

        // Check that `func` is a global function.
        if !func.is_var() {
            return StartVisitResult::VisitChildren;
        }
        let func_name = &func.get_var().name;
        if !func_name.is_global() {
            return StartVisitResult::VisitChildren;
        }

        // Check that `func` is a specializable function.
        let specializable_func = self.specializable_funcs.get(func_name);
        if specializable_func.is_none() {
            return StartVisitResult::VisitChildren;
        }
        let specialize_info = specializable_func.unwrap().clone();

        // For each specializable argument of `func`, get or generate decaptured lambda information.
        let func_origin = origin_of(&self.origins, func_name);
        let mut pinned = self.pinned.clone();
        let mut specialized_args = Map::default();
        let mut decaptured_args = args.clone();
        for (i, arg) in args.iter().enumerate() {
            // Check if this is a specializable argument.
            let slot = Slot::arg(i);
            if !specialize_info.specializable_slots.contains(&slot) {
                continue;
            }
            // Get or generate decaptured lambda information.
            if let Some(known) = self.known_value(arg) {
                if !self.commit(&mut pinned, &func_origin, slot, &known.tree.lambda) {
                    continue;
                }
                decaptured_args[i] = known.cap_list;
                specialized_args.insert(slot, known.tree);
            } else if ClosureSpecializationVisitor::decapturable(arg) {
                // TODO: maybe we don't need to handle this case, because pull-let transformation converts this argument to a variable?
                let (tree, expr) = self.decapture_lambda(arg.clone(), state); // Visits `arg` inside this call
                                                                              // A lambda written at the call site is one no chain can have met before, so this
                                                                              // only records it.
                self.commit(&mut pinned, &func_origin, slot, &tree.lambda);
                specialized_args.insert(slot, tree);
                decaptured_args[i] = expr;
            }
        }
        if specialized_args.is_empty() {
            return StartVisitResult::VisitChildren;
        }

        // Request specialization.
        let specialization = SpecializationRequest {
            org_func_name: func_name.clone(),
            org_func_ty: func.type_.as_ref().unwrap().clone(),
            specialized_args,
            pinned,
        };
        let specialized_func_expr = specialization.specialized_func_expr(&self.lifted.borrow());
        self.required_specializations.push(specialization);

        // Replace with an expression that calls the specialized function.
        let mut expr = specialized_func_expr.clone();
        for arg in decaptured_args {
            expr = expr_app_typed(expr, vec![arg]);
        }

        StartVisitResult::ReplaceAndRevisit(expr)
    }

    fn end_visit_app(&mut self, expr: &Arc<ExprNode>, _state: &mut VisitState) -> EndVisitResult {
        EndVisitResult::unchanged(expr)
    }

    fn start_visit_lam(
        &mut self,
        expr: &Arc<ExprNode>,
        _state: &mut VisitState,
    ) -> StartVisitResult {
        // Before visiting children, if the argument refers to a decaptured lambda, fix the domain part of the lambda type since it is incorrect.
        let arg = expr.get_lam_params();
        assert_eq!(arg.len(), 1);
        let arg = &arg[0];
        let arg_name = &arg.name;
        let cap_list_ty = match self.local_decap_lambdas.get(arg_name).cloned() {
            Some(known) if known.is_the_capture_list(arg_name) => self.cap_of(&known.tree).ty,
            // If the argument does not hold a capture list, do nothing.
            _ => return StartVisitResult::VisitChildren,
        };
        let lam_ty = expr.type_.as_ref().unwrap();
        let arg_ty = lam_ty.get_lambda_srcs()[0].clone();
        // If the argument type is already correct, do nothing.
        if cap_list_ty.to_string() == arg_ty.to_string() {
            return StartVisitResult::VisitChildren;
        }
        // Fix the type of this lambda expression
        let new_lambda_ty = type_fun(cap_list_ty, lam_ty.get_lambda_dst());
        let expr = expr.set_type(new_lambda_ty);
        return StartVisitResult::ReplaceAndRevisit(expr);
    }

    fn end_visit_lam(&mut self, expr: &Arc<ExprNode>, _state: &mut VisitState) -> EndVisitResult {
        // After visiting children, the codomain type of this expression may have changed, so fix the type if necessary.
        // Example: In `expr` is a lambda `|x| |y| (...)`, if `y` is a decaptured lambda, visiting `|y| (...)` may change its type, so the codomain of `|x| |y| (...)` may need to be fixed.
        let lam_ty = expr.type_.as_ref().unwrap();
        let dom_ty = lam_ty.get_lambda_srcs()[0].clone();
        let codom_ty = lam_ty.get_lambda_dst().clone();
        let lam_body = expr.get_lam_body();
        let impl_codom_ty = lam_body.type_.as_ref().unwrap();
        if codom_ty.to_string() == impl_codom_ty.to_string() {
            return EndVisitResult::unchanged(expr);
        }
        let new_lambda_ty = type_fun(dom_ty, impl_codom_ty.clone());
        let expr = expr.set_type(new_lambda_ty);
        EndVisitResult::changed(expr)
    }

    // Decapture a lambda bound by this `let`, and record the bound name in `local_decap_lambdas` so
    // that later uses of it are read as the capture list the binding now holds. A binding of a name
    // already standing for a decaptured lambda passes that reading on to the new name.
    fn start_visit_let(
        &mut self,
        expr: &Arc<ExprNode>,
        state: &mut VisitState,
    ) -> StartVisitResult {
        let pat = expr.get_let_pat();
        let bound = expr.get_let_bound();
        let value = expr.get_let_value();
        if ClosureSpecializationVisitor::decapturable(&bound) {
            // If the bound expression is a lambda, perform decapturing.
            assert!(pat.is_var());
            let var_name = pat.get_var().name.clone();
            let (tree, cap_list) = self.decapture_lambda(bound, state); // visit `bound` inside this call
            let cap_list_ty = cap_list.type_.as_ref().unwrap().clone();
            self.local_decap_lambdas.insert(
                var_name.clone(),
                Known {
                    tree,
                    cap_list: expr_var(var_name, None).set_type(cap_list_ty.clone()),
                },
            );
            let pat = pat
                .set_var_tyanno(None) // Discard type annotation since it may become incorrect
                .set_type(cap_list_ty);
            let expr = expr_let_typed(pat, cap_list, value);
            return StartVisitResult::ReplaceAndRevisit(expr);
        } else if pat.is_var() {
            // A binding whose value has a known identity passes that identity to the name it binds.
            // The binding itself is left alone: rewriting it would leave the wrapping rules
            // something to do again, and the two would take turns undoing each other.
            if let Some(known) = self.known_value(&bound) {
                self.local_decap_lambdas
                    .insert(pat.get_var().name.clone(), known);
            }
            return StartVisitResult::VisitChildren;
        } else {
            return StartVisitResult::VisitChildren;
        }
    }

    fn end_visit_let(&mut self, expr: &Arc<ExprNode>, _state: &mut VisitState) -> EndVisitResult {
        EndVisitResult::unchanged(expr)
    }

    fn start_visit_if(
        &mut self,
        _expr: &Arc<ExprNode>,
        _state: &mut VisitState,
    ) -> StartVisitResult {
        StartVisitResult::VisitChildren
    }

    fn end_visit_if(&mut self, expr: &Arc<ExprNode>, _state: &mut VisitState) -> EndVisitResult {
        EndVisitResult::unchanged(expr)
    }

    fn start_visit_match(
        &mut self,
        _expr: &Arc<ExprNode>,
        _state: &mut VisitState,
    ) -> StartVisitResult {
        StartVisitResult::VisitChildren
    }

    fn end_visit_match(&mut self, expr: &Arc<ExprNode>, _state: &mut VisitState) -> EndVisitResult {
        EndVisitResult::unchanged(expr)
    }

    fn start_visit_tyanno(
        &mut self,
        _expr: &Arc<ExprNode>,
        _state: &mut VisitState,
    ) -> StartVisitResult {
        StartVisitResult::VisitChildren
    }

    fn end_visit_tyanno(
        &mut self,
        expr: &Arc<ExprNode>,
        _state: &mut VisitState,
    ) -> EndVisitResult {
        EndVisitResult::unchanged(expr)
    }

    fn start_visit_make_struct(
        &mut self,
        _expr: &Arc<ExprNode>,
        _state: &mut VisitState,
    ) -> StartVisitResult {
        StartVisitResult::VisitChildren
    }

    fn end_visit_make_struct(
        &mut self,
        expr: &Arc<ExprNode>,
        _state: &mut VisitState,
    ) -> EndVisitResult {
        EndVisitResult::unchanged(expr)
    }

    fn start_visit_array_lit(
        &mut self,
        _expr: &Arc<ExprNode>,
        _state: &mut VisitState,
    ) -> StartVisitResult {
        StartVisitResult::VisitChildren
    }

    fn end_visit_array_lit(
        &mut self,
        expr: &Arc<ExprNode>,
        _state: &mut VisitState,
    ) -> EndVisitResult {
        EndVisitResult::unchanged(expr)
    }

    fn start_visit_ffi_call(
        &mut self,
        _expr: &Arc<ExprNode>,
        _state: &mut VisitState,
    ) -> StartVisitResult {
        StartVisitResult::VisitChildren
    }

    fn end_visit_ffi_call(
        &mut self,
        expr: &Arc<ExprNode>,
        _state: &mut VisitState,
    ) -> EndVisitResult {
        EndVisitResult::unchanged(expr)
    }

    fn start_visit_eval(
        &mut self,
        _expr: &Arc<ExprNode>,
        _state: &mut VisitState,
    ) -> StartVisitResult {
        StartVisitResult::VisitChildren
    }

    fn end_visit_eval(&mut self, expr: &Arc<ExprNode>, _state: &mut VisitState) -> EndVisitResult {
        EndVisitResult::unchanged(expr)
    }
}
