mod application_inlining;
mod capture_struct;
mod closure_specialization;
mod dead_symbol_elimination;
mod defunctionalize_fix;
#[allow(dead_code)]
mod eta_expansion;
mod find_usage_of_name;
mod inline;
mod inline_local;
mod let_elimination;
pub mod optimization;
mod optimize_act;
mod pull_let;
mod remove_tyanno;
pub mod rename;
mod simplify_symbol_names;
mod skip_eval;
mod uncurry;
mod unique_local_names;
mod unwrap_newtype;
