/*
Cache system for object (*.o) files.
*/

use std::collections::HashMap;
use std::collections::HashSet;
use std::fmt;
use std::path::PathBuf;

use rand::Rng;

use crate::ast::name::Name;
use crate::configuration::Configuration;
use crate::constants::COMPILATION_UNITS_PATH;
use crate::split_by_max_size;
use crate::InstantiatedSymbol;

pub struct CompileUnit {
    // Name of symbols in the module
    symbols: Vec<InstantiatedSymbol>,
    // Modules on which symbols in this compilation unit depends.
    dependent_modules: Vec<Name>,
    // Name of this compilation unit. Generated by hashing the names of symbols and the hashes of dependent modules.
    unit_hash: String,
}

impl fmt::Display for CompileUnit {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(
            f,
            "CompileUnit(hash = {}, size = {}, symbols = [{}, ...], dependency = [{}], is_cached = {})",
            self.unit_hash,
            self.symbols.len(),
            if self.symbols.len() > 0 {
                self.symbols[0].instantiated_name.to_string()
            } else {
                "N/A".to_string()
            },
            self.dependent_modules.join(", "),
            self.is_cached()
        )
    }
}

impl CompileUnit {
    pub fn new(symbols: Vec<InstantiatedSymbol>, dependent_modules: Vec<Name>) -> Self {
        CompileUnit {
            symbols,
            dependent_modules,
            unit_hash: "".to_string(),
        }
    }

    pub fn unit_hash(&self) -> &str {
        &self.unit_hash
    }

    pub fn symbols(&self) -> &[InstantiatedSymbol] {
        &self.symbols
    }

    pub fn is_cached(&self) -> bool {
        self.object_file_path().exists()
    }

    pub fn object_file_path(&self) -> PathBuf {
        if self.unit_hash.len() == 0 {
            panic!("unit_hash is not set.");
        }
        let mut path = PathBuf::from(COMPILATION_UNITS_PATH);
        let file_name = self.unit_hash.to_string() + ".o";
        path.push(file_name);
        path
    }

    // Calculate the hash of this compilation unit and set it to `self`.
    fn update_unit_hash(
        &mut self,
        module_dependency_hash: &HashMap<Name, String>,
        config: &Configuration,
    ) {
        if self.unit_hash.len() > 0 {
            return;
        }
        assert!(self.symbols.len() > 0);
        assert!(self.dependent_modules.len() > 0);

        self.symbols.sort_by(|a, b| {
            a.instantiated_name
                .to_string()
                .cmp(&b.instantiated_name.to_string())
        });
        self.dependent_modules.sort();

        // Add dependency to the configuration.
        let mut data = vec![];
        data.push("<configuration>".to_string());
        data.push(config.object_generation_hash());

        // Add dependency to the symbols.
        data.push("<symbols>".to_string());
        for symbol in &self.symbols {
            data.push(symbol.instantiated_name.to_string());
        }

        // Add dependency to source codes of the dependent modules.
        data.push("<dependent modules>".to_string());
        for name in &self.dependent_modules {
            data.push(module_dependency_hash[name].clone());
        }

        self.unit_hash = format!("{:x}", md5::compute(data.join(", ")));
    }

    // Set the hash of this compilation unit to a random value.
    // This makes the compilation unit to be recompiled always.
    pub fn set_random_unit_hash(&mut self) {
        assert!(self.unit_hash.len() == 0);
        self.unit_hash = format!(
            "{:x}",
            md5::compute(rand::thread_rng().gen::<u64>().to_string())
        );
    }

    pub fn split_by_max_size(self, max_size: usize) -> Vec<CompileUnit> {
        // `unit_hash` is lost after this method is called.
        assert_eq!(self.unit_hash, "");

        let symbols = self.symbols;
        let dependent_modules = self.dependent_modules;

        let split_symbols = split_by_max_size(symbols, max_size);
        let mut units = vec![];
        for symbols in split_symbols {
            units.push(CompileUnit::new(symbols, dependent_modules.clone()));
        }

        units
    }

    // Given a sequence of symbols, split it into compilation units.
    pub fn split_symbols(
        symbols: Vec<InstantiatedSymbol>,
        module_dependency_hash: &HashMap<Name, String>,
        module_dependency_map: &HashMap<Name, HashSet<Name>>,
        config: &Configuration,
    ) -> Vec<CompileUnit> {
        let mut units: HashMap<
            String, /* concatenated string of dependent modules sorted by their names */
            CompileUnit,
        > = HashMap::new();
        // Classify symbols into compilation units depending on their dependent modules.
        for symbol in symbols {
            let mut depmods = HashSet::new();
            for module in symbol.dependent_modules() {
                depmods.extend(module_dependency_map[&module].clone());
            }
            let mut depmods = depmods.iter().cloned().collect::<Vec<_>>();
            depmods.sort();
            let concat_depmods = depmods.join(", ");
            let unit = if let Some(unit) = units.get_mut(&concat_depmods) {
                unit
            } else {
                units.insert(concat_depmods.clone(), CompileUnit::new(vec![], depmods));
                units.get_mut(&concat_depmods).unwrap()
            };
            unit.symbols.push(symbol);
        }
        let mut units = units.into_iter().map(|(_, unit)| unit).collect::<Vec<_>>();
        for unit in &mut units {
            unit.symbols.sort_by(|a, b| {
                a.instantiated_name
                    .to_string()
                    .partial_cmp(&b.instantiated_name.to_string())
                    .unwrap()
            });
        }

        // Split compilation units into smaller ones if they are too large.
        let mut units = units
            .into_iter()
            .flat_map(|unit| unit.split_by_max_size(config.max_cu_size))
            .collect::<Vec<_>>();

        // Set unit hash.
        for unit in &mut units {
            unit.update_unit_hash(module_dependency_hash, config);
        }

        units
    }
}
