// This source file is generated by by passes_optimizer.py.

use super::*;
use inkwell::passes::PassManagerSubType;

pub fn add_passes<T: PassManagerSubType>(passmgr: &PassManager<T>) {
    passmgr.add_scalar_repl_aggregates_pass();
    passmgr.add_function_inlining_pass();
    passmgr.add_ind_var_simplify_pass();
    passmgr.add_cfg_simplification_pass();
    passmgr.add_early_cse_pass();
    passmgr.add_sccp_pass();
    passmgr.add_loop_deletion_pass();
    passmgr.add_scalar_repl_aggregates_pass_ssa();
    passmgr.add_global_dce_pass();
    passmgr.add_alignment_from_assumptions_pass();
    passmgr.add_type_based_alias_analysis_pass();
    passmgr.add_aggressive_dce_pass();
    passmgr.add_strip_dead_prototypes_pass();
    passmgr.add_scoped_no_alias_aa_pass();
    passmgr.add_merge_functions_pass();
    passmgr.add_global_optimizer_pass();
    passmgr.add_scalarizer_pass();
    passmgr.add_jump_threading_pass();
}
